### ISSUE TITLE
Status of the gem

### ISSUE THREAD

**Issue by remino** [Interactive-Gaming-Entertainment/safecharge-api#1]
Hi,

I'm a developer currently working on a project in which a Rails 4 application will use Gate2Shop as its payment processing provider. Gate2Shop uses Safecharge to perform the transaction.

Although your README states the gem is not ready for production, my team and I thought it was at least a good start for us to use the gem and at least try to work with it.

But it seems to be missing quite a few important parts. For example, the README is not describing how the Safecharge URL needs to be set before the `Safecharge.request_url` helper can be used. Also, the format of the parameters sent to Safecharge does not seem to match the format described in our API documentation provided by Gate2Shop (for example: the parameter name `sg_Amount` should be used instead of `total_amount`).

We were wondering what is the state of the gem. When you described the gem is in "active development," did you mean that it was not usable at all at the moment? Were you able to use your own gem to perform payment transactions for your own projects?

Please let us know.

**Comment by davesag** [comment]
Hi @remino we are using the Gem internally here to talk to Safecharge.  You need to ensure that some environment variables are set up in order for it to work.  I'll update the README shortly but the env vars are:

```
SAFECHARGE_SERVER_TEST=_supplied_by_safecharge_
SAFECHARGE_SERVER_LIVE=_supplied_by_safecharge_
SAFECHARGE_SECRET_KEY=_supplied_by_safecharge_
SAFECHARGE_MERCHANT_ID=_supplied_by_safecharge_ 
SAFECHARGE_MERCHANT_SITE_ID=_supplied_by_safecharge_
SAFECHARGE_MERCHANT_3D_SITE_ID=_supplied_by_safecharge_
SAFECHARGE_SG_CLIENT_PASSWORD=_supplied_by_safecharge_
SAFECHARGE_SG_3D_CLIENT_PASSWORD=_supplied_by_safecharge_
SAFECHARGE_CPANEL_PASSWORD=_supplied_by_safecharge_
```

I've not done the `gateway integration` part yet as we don't need it for what we are doing. We are using the WebCashier and DMN stuff, so that's the bits I've implemented.  Feel free to fork and add other request types.

**Comment by remino** [comment]
Hi @davesag,

As I'm new to Safecharge, I wasn't aware of the differences between the different kinds of integrations, including "gateway integration." After learning this, it looks like we'll simply use Gate2Shop's processing instead of going through them to use Safecharge directly.

Thanks for your response!
